# User's complete list from the last message (cleaning duplicates)
user_teams = [
    "Aba Elephants",
    "Abidjan Yellows",
    "Adelaide United",
    "Al-Fateh",
    "Al-Fayha",
    "Al-Hazem",
    "Al-Khaleej",
    "Al-Kholood",
    "Al-Najma",
    "Al-Okhdood",
    "Al-Qadsiah",
    "Al-Riyadh",
    "Al-Taawoun",
    "Alajuelense",
    "Alanya Sun",
    "Algiers Reds",
    "Algiers Union",
    "AmaZulu FC",
    "Angers Black-Whites",
    "Antalya Scorpions",
    "London Cannons",
    "AS FAR",
    "Birmingham Villans",
    "Bergamo United",
    "Atlanta Stripes",
    "Atlántico Blue Stars",
    "Auckland FC",
    "Augsburg Falcons",
    "Austin Verdes",
    "AJ Burgundy",
    "Avellaneda Devils",
    "Avellaneda Racers",
    "Avispa Fukuoka",
    "Banfield Drills",
    "Bank El Ahly",
    "Barbados Royal Club",
    "Barracas Truckers",
    "Barranquilla Sharks",
    "Basak City",
    "Leverkusen Red",
    "Munich Red",
    "Belém Lions",
    "Belo Horizonte Cruisers",
    "Belo Horizonte Miners",
    "Belvedere Blue",
    "Bilbao Lions",
    "Bochum Blue",
    "Boedo Saints",
    "Bogotá Blues",
    "Bogotá Cardinals",
    "Bogotá Fort",
    "Cagliari Islanders",
    "Cairo Knights",
    "Cairo Red Devils",
    "Calera Red",
    "Cali Devils",
    "Cali Sugar",
    "Cape Town City",
    "Casablanca Eagles",
    "Casablanca Reds",
    "Catalonia Blau",
    "Cavalier Town FC",
    "Cavaly SC",
    "Daejeon Hana Citizen",
    "Dallas Burn",
    "Damac FC",
    "Dammam Commandos",
    "Dar Citizens",
    "Dar Lions",
    "Desert Miners",
    "Difaâ El Jadidi",
    "Doha Sadd",
    "Westphalia Yellows",
    "Bucaramanga Leopards",
    "Bucheon FC 1995",
    "Buenos Aires Millionaires",
    "Buenos Aires Storm",
    "Buriram Thunder",
    "Lancashire Clarets",
    "El Gouna",
    "El Masry",
    "El Mokawloon",
    "Enppi",
    "Espanyol Parrots",
    "Merseyside Blues",
    "Eyup Violet",
    "Fagiano Okayama",
    "FC Anyang",
    "FC Tokyo",
    "Istanbul Yellows",
    "Florence Viola",
    "Frankfurt Eagles",
    "Freiburg Forest",
    "West London Whites",
    "FUS Rabat",
    "Galata Lions",
    "Galaxy Stars",
    "Gamba Osaka",
    "Gangwon FC",
    "Gauchos Gold",
    "Izmir Goz",
    "Guadalajara Foxes",
    "Guadalajara Goats",
    "Guyana Amazon FC",
    "Gwangju FC",
    "Giza Pyramids",
    "Gladbach Foals",
    "Golden Arrows",
    "South Madrid Blues",
    "Ghazl El Mahalla",
    "Gimcheon Sangmu",
    "Girona Reds",
    "San Jose Purple",
    "Alajuela Lions",
    "Heredia Red-Yellow",
    "Cartago Blues",
    "San Carlos Bulls",
    "San Isidro Warriors",
    "Puntarenas Sharks",
    "Sporting Jose",
    "Liberia Gold",
    "Guadalupe Blue",
    "Chapecó Eagles",
    "Charlotte Crowns",
    "Chicago Firemen",
    "London Blue Lions",
    "Chillan Red",
    "Cibao Orange FC",
    "Cincinnati Royals",
    "Citadel Saints",
    "City of Melbourne",
    "Cleopatra FC",
    "Club Africain",
    "COD Meknès",
    "Columbus Crew",
    "Como Lakers",
    "Concepción Purple",
    "Concepción Uni",
    "Coquimbo Pirates",
    "Cordoba Glory",
    "Cordoba Pirates",
    "Cordoba Tall",
    "Crystal Glaziers",
    "Cucuta Border",
    "Curitiba Greens",
    "Curitiba Storm",
    "Genoa Griffins",
    "Antep Falcons",
    "Ankara Youth"
]

print(f"Total unique teams in user's list: {len(set(user_teams))}")

# Check which ones are in constants.ts
import re

with open('constants.ts', 'r', encoding='utf-8') as f:
    content = f.read()

found = []
missing = []

for team in set(user_teams):
    pattern = f'"{re.escape(team)}"\\s*:'
    if re.search(pattern, content):
        found.append(team)
    else:
        missing.append(team)

print(f"\n✅ Found in constants.ts: {len(found)}")
print(f"❌ Missing from constants.ts: {len(missing)}")

if missing:
    print("\n🔴 MISSING TEAMS:")
    for team in sorted(missing):
        print(f"  - {team}")
else:
    print("\n🎉 ALL TEAMS ARE IN THE FILE!")
